# Generated by Django 5.0.3 on 2024-03-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('pswd', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('user_type', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
