# Generated by Django 4.2.11 on 2024-03-31 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='website',
            field=models.CharField(default='', max_length=30),
        ),
    ]
