# Generated by Django 4.2.11 on 2024-03-31 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tbl_user_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_jobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='', max_length=30)),
                ('experience', models.CharField(default='', max_length=50)),
                ('qualification', models.CharField(default='', max_length=30)),
                ('skills', models.CharField(default='', max_length=30)),
                ('requirements', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('cmpny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_user')),
            ],
        ),
    ]
