# Generated by Django 4.2.11 on 2024-04-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_tbl_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_jobpost',
            name='end_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_jobpost',
            name='joblocation',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_jobpost',
            name='responsibilities',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_jobpost',
            name='salary',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_jobpost',
            name='upload_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
