# Generated by Django 4.2.11 on 2024-04-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_tbl_jobrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('phone', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('pswd', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='', max_length=30)),
                ('website', models.CharField(default='', max_length=30)),
                ('user_type', models.CharField(default='company', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='tbl_user',
            name='website',
        ),
    ]
