# Generated by Django 4.2.11 on 2024-04-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_tbl_company_remove_tbl_user_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_jobrequest',
            name='cmp_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_company'),
        ),
        migrations.AlterField(
            model_name='tbl_jobpost',
            name='cmpny',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_company'),
        ),
    ]
