# Generated by Django 4.2.11 on 2024-04-21 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_tbl_jobrequest_cmp_id_alter_tbl_jobpost_cmpny'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_jobrequest',
            name='interview_date',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_jobrequest',
            name='interview_location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tbl_jobrequest',
            name='interview_time',
            field=models.CharField(default='', max_length=100),
        ),
    ]
