# Generated by Django 4.2.11 on 2024-04-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_tbl_jobrequest_interview_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbl_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(default='', max_length=30)),
                ('feedback', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=30)),
                ('cmpny', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.tbl_user')),
            ],
        ),
    ]
