# Generated by Django 4.2.11 on 2024-04-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_tbl_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_feedback',
            name='utype',
            field=models.CharField(default='', max_length=30),
        ),
    ]
