# Generated by Django 4.2.11 on 2024-04-21 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_tbl_feedback_utype'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='qualification',
            field=models.CharField(default='', max_length=50),
        ),
    ]
